from django.db import models


class NetworkChoice(models.TextChoices):
    TELEGRAM = "TG", "Telegram"
    INSTAGRAM = "IG", "Instagram"
    GITHUB = "GH", "GitHub"
    LINKEDIN = "LI", "LinkedIn"


class SkillChoice(models.TextChoices):
    PYTHON = "PY", "Python"
    JAVASCRIPT = "JS", "JavaScript"
    TYPESCRIPT = "TS", "TypeScript"
    GOLANG = "GO", "Go"
    RUST = "RS", "Rust"
    C_SHARP = "CS", "C#"
    C_PLUS_PLUS = "CPP", "C++"
    JAVA = "JV", "Java"
    KOTLIN = "KT", "Kotlin"
    SWIFT = "SW", "Swift"
    PHP = "PHP", "PHP"
    RUBY = "RB", "Ruby"
    SCALA = "SC", "Scala"
    DART = "DT", "Dart"
    SHELL = "SH", "Bash/Shell"
    ZIG = "ZG", "Zig"

    DJANGO = "DJ", "Django"
    FASTAPI = "FA", "FastAPI"
    FLASK = "FL", "Flask"
    SPRING_BOOT = "SB", "Spring Boot"
    NODE_JS = "NODE", "Node.js"
    EXPRESS = "EXPR", "Express"
    NEST_JS = "NEST", "NestJS"
    ASP_NET = "ASP", "ASP.NET"
    LARAVEL = "LV", "Laravel"
    SYMFONY = "SYM", "Symfony"
    RUBY_ON_RAILS = "ROR", "Rails"

    HTML5 = "HTML", "HTML/CSS"
    REACT = "REA", "React"
    VUE_JS = "VUE", "Vue"
    ANGULAR = "ANG", "Angular"
    NEXT_JS = "NEXT", "Next.js"
    NUXT_JS = "NUXT", "Nuxt.js"
    SVELTE = "SVEL", "Svelte"
    TAILWIND_CSS = "TW", "Tailwind"
    SASS_SCSS = "SASS", "SASS/SCSS"
    REDUX = "RDX", "Redux"
    WEBPACK = "WP", "Webpack"
    VITE = "VT", "Vite"
    HTMX = "HTMX", "htmx"
    SOLID_JS = "SLD", "SolidJS"

    POSTGRESQL = "PG", "PostgreSQL"
    MYSQL = "MY", "MySQL"
    MONGODB = "MG", "MongoDB"
    REDIS = "RDS", "Redis"
    ELASTICSEARCH = "ES", "Elasticsearch"
    SQLITE = "SQ", "SQLite"
    MARIADB = "MAR", "MariaDB"
    CASSANDRA = "CAS", "Cassandra"
    NEO4J = "N4J", "Neo4j"
    CLICKHOUSE = "CH", "ClickHouse"
    MEMCACHED = "MEM", "Memcached"
    SUPABASE = "SUPA", "Supabase"
    SURREALDB = "SRL", "SurrealDB"

    FLUTTER = "FLTR", "Flutter"
    REACT_NATIVE = "RN", "React Native"
    ANDROID_SDK = "AND", "Android"
    IOS_SDK = "IOS", "iOS"
    XAMARIN = "XAM", "Xamarin"

    DOCKER = "DKR", "Docker"
    KUBERNETES = "K8S", "Kubernetes"
    AWS = "AWS", "AWS"
    GOOGLE_CLOUD = "GCP", "GCP"
    AZURE = "AZR", "Azure"
    TERRAFORM = "TFMM", "Terraform"
    ANSIBLE = "ANS", "Ansible"
    JENKINS = "JNK", "Jenkins"
    GITHUB_ACTIONS = "GHA", "GitHub Actions"
    GITLAB_CI = "GLCI", "GitLab CI"
    NGINX = "NGX", "Nginx"
    APACHE = "APCH", "Apache"
    PODMAN = "PDM", "Podman"

    NUMPY_PANDAS = "NPD", "NumPy/Pandas"
    TENSORFLOW = "TF", "TensorFlow"
    PYTORCH = "PT", "PyTorch"
    SCIKIT_LEARN = "SKL", "Scikit-Learn"
    LANGCHAIN = "LC", "LangChain"
    OPENAI_API = "OAI", "OpenAI"
    APACHE_SPARK = "SPK", "Spark"
    HADOOP = "HDP", "Hadoop"
    MATLAB = "MTL", "MATLAB"
    HUGGING_FACE = "HF", "Hugging Face"
    LLAMA_INDEX = "LLM", "LlamaIndex"

    GIT = "GIT", "Git"
    REST_API = "REST", "REST"
    GRAPHQL = "GQL", "GraphQL"
    GRPC = "GRPC", "gRPC"
    WEB_SOCKETS = "WS", "WebSockets"
    RABBITMQ = "RMQ", "RabbitMQ"
    APACHE_KAFKA = "KFK", "Kafka"
    CELERY = "CEL", "Celery"
    LINUX_ADMIN = "LINX", "Linux"
    MICROSERVICES = "MSVC", "Microservices"
    UNIT_TESTING = "TEST", "Testing"
    SELENIUM = "SEL", "Selenium"
    PLAYWRIGHT = "PW", "Playwright"
    CI_CD = "CICD", "CI/CD"


class LanguageChoice(models.TextChoices):
    ENGLISH = "ENG", "English"
    UKRAINIAN = "UKR", "Ukrainian"
    GERMAN = "DEU", "German"
    POLISH = "POL", "Polish"
    SPANISH = "SPA", "Spanish"
    FRENCH = "FRA", "French"
    ITALIAN = "ITA", "Italian"
    CHINESE = "ZHO", "Chinese"
    JAPANESE = "JPN", "Japanese"


class LanguageLevelChoices(models.TextChoices):
    A1 = "A1", "Beginner"
    A2 = "A2", "Elementary"
    B1 = "B1", "Intermediate"
    B2 = "B2", "Upper-Intermediate"
    C1 = "C1", "Advanced"
    C2 = "C2", "Native"


class DegreeChoices(models.TextChoices):
    ASSOCIATE = "ASSOC", "Associate"
    BACHELOR = "BACH", "Bachelor"
    MASTER = "MAST", "Master"
    DOCTORATE = "DOC", "Doctorate"
    PROFESSIONAL = "PROF", "Professional"