from django.db import models


class NetworkChoice(models.TextChoices):
    TELEGRAM = "TG", "Telegram"
    INSTAGRAM = "IG", "Instagram"
    GITHUB = "GH", "GitHub"
    LINKEDIN = "LI", "LinkedIn"


class SkillChoice(models.TextChoices):
    PYTHON = "PYTHON", "Python"
    JAVASCRIPT = "JS", "JavaScript"
    TYPESCRIPT = "TS", "TypeScript"
    GOLANG = "GO", "Go (Golang)"
    RUST = "RUST", "Rust"
    C_SHARP = "CSHARP", "C#"
    C_PLUS_PLUS = "CPP", "C++"
    JAVA = "JAVA", "Java"
    KOTLIN = "KOTLIN", "Kotlin"
    SWIFT = "SWIFT", "Swift"
    PHP = "PHP", "PHP"
    RUBY = "RUBY", "Ruby"
    SCALA = "SCALA", "Scala"
    DART = "DART", "Dart"
    SHELL = "SHELL", "Bash / Shell Scripting"

    DJANGO = "DJANGO", "Django / Django REST Framework"
    FASTAPI = "FASTAPI", "FastAPI"
    FLASK = "FLASK", "Flask"
    SPRING_BOOT = "SPRING", "Spring Boot"
    NODE_JS = "NODEJS", "Node.js"
    EXPRESS = "EXPRESS", "Express.js"
    NEST_JS = "NESTJS", "NestJS"
    ASP_NET = "ASPNET", "ASP.NET Core"
    LARAVEL = "LARAVEL", "Laravel"
    SYMFONY = "SYMFONY", "Symfony"
    RUBY_ON_RAILS = "RAILS", "Ruby on Rails"

    HTML5 = "HTML5", "HTML5 & CSS3"
    REACT = "REACT", "React.js"
    VUE_JS = "VUE", "Vue.js"
    ANGULAR = "ANGULAR", "Angular"
    NEXT_JS = "NEXTJS", "Next.js"
    NUXT_JS = "NUXTJS", "Nuxt.js"
    SVELTE = "SVELTE", "Svelte"
    TAILWIND_CSS = "TAILWIND", "Tailwind CSS"
    SASS_SCSS = "SASS", "SASS / SCSS"
    REDUX = "REDUX", "Redux / Redux Toolkit"
    WEBPACK = "WEBPACK", "Webpack"
    VITE = "VITE", "Vite"

    POSTGRESQL = "POSTGRES", "PostgreSQL"
    MYSQL = "MYSQL", "MySQL"
    MONGODB = "MONGODB", "MongoDB"
    REDIS = "REDIS", "Redis"
    ELASTICSEARCH = "ELASTIC", "Elasticsearch"
    SQLITE = "SQLITE", "SQLite"
    MARIADB = "MARIADB", "MariaDB"
    CASSANDRA = "CASSANDRA", "Apache Cassandra"
    NEO4J = "NEO4J", "Neo4j (Graph DB)"
    CLICKHOUSE = "CLICKHOUSE", "ClickHouse"
    MEMCACHED = "MEMCACHED", "Memcached"

    FLUTTER = "FLUTTER", "Flutter"
    REACT_NATIVE = "REACT_NAT", "React Native"
    ANDROID_SDK = "ANDROID", "Android SDK"
    IOS_SDK = "IOS", "iOS SDK"
    XAMARIN = "XAMARIN", "Xamarin"

    DOCKER = "DOCKER", "Docker"
    KUBERNETES = "KUBE", "Kubernetes (K8s)"
    AWS = "AWS", "Amazon Web Services (AWS)"
    GOOGLE_CLOUD = "GCP", "Google Cloud Platform (GCP)"
    AZURE = "AZURE", "Microsoft Azure"
    TERRAFORM = "TERRAFORM", "Terraform"
    ANSIBLE = "ANSIBLE", "Ansible"
    JENKINS = "JENKINS", "Jenkins"
    GITHUB_ACTIONS = "GHACTIONS", "GitHub Actions"
    GITLAB_CI = "GITLABCI", "GitLab CI/CD"
    NGINX = "NGINX", "Nginx"
    APACHE = "APACHE", "Apache HTTP Server"

    NUMPY_PANDAS = "NUMPY_PANDAS", "NumPy & Pandas"
    TENSORFLOW = "TF", "TensorFlow"
    PYTORCH = "PYTORCH", "PyTorch"
    SCIKIT_LEARN = "SCIKIT", "Scikit-Learn"
    LANGCHAIN = "LANGCHAIN", "LangChain"
    OPENAI_API = "OPENAI", "OpenAI API / LLM"
    APACHE_SPARK = "SPARK", "Apache Spark"
    HADOOP = "HADOOP", "Apache Hadoop"
    MATLAB = "MATLAB", "MATLAB"

    GIT = "GIT", "Git / GitHub / GitLab"
    REST_API = "REST", "RESTful APIs"
    GRAPHQL = "GRAPHQL", "GraphQL"
    GRPC = "GRPC", "gRPC"
    WEB_SOCKETS = "WEBSOCKET", "WebSockets"
    RABBITMQ = "RABBITMQ", "RabbitMQ"
    APACHE_KAFKA = "KAFKA", "Apache Kafka"
    CELERY = "CELERY", "Celery"
    LINUX_ADMIN = "LINUX", "Linux System Administration"
    MICROSERVICES = "MICROSERVICES", "Microservices Architecture"
    UNIT_TESTING = "TESTING", "Unit Testing (PyTest, Jest, JUnit)"
    SELENIUM = "SELENIUM", "Selenium / Playwright"


class LanguageChoice(models.TextChoices):
    ENGLISH = "ENG", "English"
    UKRAINIAN = "UKR", "Ukrainian"
    GERMAN = "DEU", "German"
    POLISH = "POL", "Polish"
    SPANISH = "SPA", "Spanish"
    FRENCH = "FRA", "French"
    ITALIAN = "ITA", "Italian"
    CHINESE = "ZHO", "Chinese"
    JAPANESE = "JPN", "Japanese"


class LanguageLevelChoices(models.TextChoices):
    A1 = "A1", "Beginner"
    A2 = "A2", "Elementary"
    B1 = "B1", "Intermediate"
    B2 = "B2", "Upper-Intermediate"
    C1 = "C1", "Advanced"
    C2 = "C2", "Native"