# Generated by Django 6.0.5 on 2026-05-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_resumetemplate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetemplate',
            name='description',
        ),
    ]
