# Generated by Django 6.0.5 on 2026-05-27 13:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_resumetemplate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='preview_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
