# Generated by Django 6.0.5 on 2026-05-23 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_position', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='work_profile.workprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(max_length=64)),
                ('specialty', models.CharField(max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='work_profile.workprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TG', 'Telegram'), ('IG', 'Instagram'), ('GH', 'GitHub'), ('LI', 'LinkedIn')], max_length=2)),
                ('link', models.URLField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='work_profile.workprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'type'), name='unique_social_type_for_user')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PYTHON', 'Python'), ('JS', 'JavaScript'), ('TS', 'TypeScript'), ('GO', 'Go (Golang)'), ('RUST', 'Rust'), ('CSHARP', 'C#'), ('CPP', 'C++'), ('JAVA', 'Java'), ('KOTLIN', 'Kotlin'), ('SWIFT', 'Swift'), ('PHP', 'PHP'), ('RUBY', 'Ruby'), ('SCALA', 'Scala'), ('DART', 'Dart'), ('SHELL', 'Bash / Shell Scripting'), ('DJANGO', 'Django / Django REST Framework'), ('FASTAPI', 'FastAPI'), ('FLASK', 'Flask'), ('SPRING', 'Spring Boot'), ('NODEJS', 'Node.js'), ('EXPRESS', 'Express.js'), ('NESTJS', 'NestJS'), ('ASPNET', 'ASP.NET Core'), ('LARAVEL', 'Laravel'), ('SYMFONY', 'Symfony'), ('RAILS', 'Ruby on Rails'), ('HTML5', 'HTML5 & CSS3'), ('REACT', 'React.js'), ('VUE', 'Vue.js'), ('ANGULAR', 'Angular'), ('NEXTJS', 'Next.js'), ('NUXTJS', 'Nuxt.js'), ('SVELTE', 'Svelte'), ('TAILWIND', 'Tailwind CSS'), ('SASS', 'SASS / SCSS'), ('REDUX', 'Redux / Redux Toolkit'), ('WEBPACK', 'Webpack'), ('VITE', 'Vite'), ('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('MONGODB', 'MongoDB'), ('REDIS', 'Redis'), ('ELASTIC', 'Elasticsearch'), ('SQLITE', 'SQLite'), ('MARIADB', 'MariaDB'), ('CASSANDRA', 'Apache Cassandra'), ('NEO4J', 'Neo4j (Graph DB)'), ('CLICKHOUSE', 'ClickHouse'), ('MEMCACHED', 'Memcached'), ('FLUTTER', 'Flutter'), ('REACT_NAT', 'React Native'), ('ANDROID', 'Android SDK'), ('IOS', 'iOS SDK'), ('XAMARIN', 'Xamarin'), ('DOCKER', 'Docker'), ('KUBE', 'Kubernetes (K8s)'), ('AWS', 'Amazon Web Services (AWS)'), ('GCP', 'Google Cloud Platform (GCP)'), ('AZURE', 'Microsoft Azure'), ('TERRAFORM', 'Terraform'), ('ANSIBLE', 'Ansible'), ('JENKINS', 'Jenkins'), ('GHACTIONS', 'GitHub Actions'), ('GITLABCI', 'GitLab CI/CD'), ('NGINX', 'Nginx'), ('APACHE', 'Apache HTTP Server'), ('NUMPY_PANDAS', 'NumPy & Pandas'), ('TF', 'TensorFlow'), ('PYTORCH', 'PyTorch'), ('SCIKIT', 'Scikit-Learn'), ('LANGCHAIN', 'LangChain'), ('OPENAI', 'OpenAI API / LLM'), ('SPARK', 'Apache Spark'), ('HADOOP', 'Apache Hadoop'), ('MATLAB', 'MATLAB'), ('GIT', 'Git / GitHub / GitLab'), ('REST', 'RESTful APIs'), ('GRAPHQL', 'GraphQL'), ('GRPC', 'gRPC'), ('WEBSOCKET', 'WebSockets'), ('RABBITMQ', 'RabbitMQ'), ('KAFKA', 'Apache Kafka'), ('CELERY', 'Celery'), ('LINUX', 'Linux System Administration'), ('MICROSERVICES', 'Microservices Architecture'), ('TESTING', 'Unit Testing (PyTest, Jest, JUnit)'), ('SELENIUM', 'Selenium / Playwright')], max_length=20)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='work_profile.workprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'type'), name='unique_skill_type_for_user')],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ENG', 'English'), ('UKR', 'Ukrainian'), ('DEU', 'German'), ('POL', 'Polish'), ('SPA', 'Spanish'), ('FRA', 'French'), ('ITA', 'Italian'), ('ZHO', 'Chinese'), ('JPN', 'Japanese')], max_length=20)),
                ('level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Native')], max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='work_profile.workprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'language'), name='unique_language_for_user')],
            },
        ),
    ]
