# Generated by Django 6.0.5 on 2026-05-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workprofile",
            name="desired_position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="workprofile",
            name="summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
