# Generated by Django 6.0.5 on 2026-05-24 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work_profile", "0002_alter_workprofile_desired_position_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationexperience",
            options={"ordering": ("-started_at",)},
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={"ordering": ("-started_at",)},
        ),
    ]
