# Generated by Django 6.0.5 on 2026-05-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_profile', '0004_alter_workprofile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationexperience',
            name='specialty',
            field=models.CharField(choices=[('ASSOC', 'Associate'), ('BACH', 'Bachelor'), ('MASR', 'Master'), ('DOC', 'Doctorate'), ('PROF', 'Professional')], max_length=5),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('UKR', 'Ukrainian'), ('DEU', 'German'), ('POL', 'Polish'), ('SPA', 'Spanish'), ('FRA', 'French'), ('ITA', 'Italian'), ('ZHO', 'Chinese'), ('JPN', 'Japanese')], default='ENG', max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Native')], default='C2', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JS', 'JavaScript'), ('TS', 'TypeScript'), ('GO', 'Go (Golang)'), ('RUST', 'Rust'), ('CSHARP', 'C#'), ('CPP', 'C++'), ('JAVA', 'Java'), ('KOTLIN', 'Kotlin'), ('SWIFT', 'Swift'), ('PHP', 'PHP'), ('RUBY', 'Ruby'), ('SCALA', 'Scala'), ('DART', 'Dart'), ('SHELL', 'Bash / Shell Scripting'), ('DJANGO', 'Django / Django REST Framework'), ('FASTAPI', 'FastAPI'), ('FLASK', 'Flask'), ('SPRING', 'Spring Boot'), ('NODEJS', 'Node.js'), ('EXPRESS', 'Express.js'), ('NESTJS', 'NestJS'), ('ASPNET', 'ASP.NET Core'), ('LARAVEL', 'Laravel'), ('SYMFONY', 'Symfony'), ('RAILS', 'Ruby on Rails'), ('HTML5', 'HTML5 & CSS3'), ('REACT', 'React.js'), ('VUE', 'Vue.js'), ('ANGULAR', 'Angular'), ('NEXTJS', 'Next.js'), ('NUXTJS', 'Nuxt.js'), ('SVELTE', 'Svelte'), ('TAILWIND', 'Tailwind CSS'), ('SASS', 'SASS / SCSS'), ('REDUX', 'Redux / Redux Toolkit'), ('WEBPACK', 'Webpack'), ('VITE', 'Vite'), ('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('MONGODB', 'MongoDB'), ('REDIS', 'Redis'), ('ELASTIC', 'Elasticsearch'), ('SQLITE', 'SQLite'), ('MARIADB', 'MariaDB'), ('CASSANDRA', 'Apache Cassandra'), ('NEO4J', 'Neo4j (Graph DB)'), ('CLICKHOUSE', 'ClickHouse'), ('MEMCACHED', 'Memcached'), ('FLUTTER', 'Flutter'), ('REACT_NAT', 'React Native'), ('ANDROID', 'Android SDK'), ('IOS', 'iOS SDK'), ('XAMARIN', 'Xamarin'), ('DOCKER', 'Docker'), ('KUBE', 'Kubernetes (K8s)'), ('AWS', 'Amazon Web Services (AWS)'), ('GCP', 'Google Cloud Platform (GCP)'), ('AZURE', 'Microsoft Azure'), ('TERRAFORM', 'Terraform'), ('ANSIBLE', 'Ansible'), ('JENKINS', 'Jenkins'), ('GHACTIONS', 'GitHub Actions'), ('GITLABCI', 'GitLab CI/CD'), ('NGINX', 'Nginx'), ('APACHE', 'Apache HTTP Server'), ('NUMPY_PANDAS', 'NumPy & Pandas'), ('TF', 'TensorFlow'), ('PYTORCH', 'PyTorch'), ('SCIKIT', 'Scikit-Learn'), ('LANGCHAIN', 'LangChain'), ('OPENAI', 'OpenAI API / LLM'), ('SPARK', 'Apache Spark'), ('HADOOP', 'Apache Hadoop'), ('MATLAB', 'MATLAB'), ('GIT', 'Git / GitHub / GitLab'), ('REST', 'RESTful APIs'), ('GRAPHQL', 'GraphQL'), ('GRPC', 'gRPC'), ('WEBSOCKET', 'WebSockets'), ('RABBITMQ', 'RabbitMQ'), ('KAFKA', 'Apache Kafka'), ('CELERY', 'Celery'), ('LINUX', 'Linux System Administration'), ('MICROSERVICES', 'Microservices Architecture'), ('TESTING', 'Unit Testing (PyTest, Jest, JUnit)'), ('SELENIUM', 'Selenium / Playwright')], default='PYTHON', max_length=20),
        ),
        migrations.AlterField(
            model_name='social',
            name='type',
            field=models.CharField(choices=[('TG', 'Telegram'), ('IG', 'Instagram'), ('GH', 'GitHub'), ('LI', 'LinkedIn')], default='IG', max_length=2),
        ),
    ]
