# Generated by Django 6.0.5 on 2026-05-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_profile', '0006_alter_educationexperience_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationexperience',
            name='ended_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='ended_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
