# Generated by Django 6.0.5 on 2026-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_profile', '0008_alter_educationexperience_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('TS', 'TypeScript'), ('GO', 'Go'), ('RS', 'Rust'), ('CS', 'C#'), ('CPP', 'C++'), ('JV', 'Java'), ('KT', 'Kotlin'), ('SW', 'Swift'), ('PHP', 'PHP'), ('RB', 'Ruby'), ('SC', 'Scala'), ('DT', 'Dart'), ('SH', 'Bash/Shell'), ('ZG', 'Zig'), ('DJ', 'Django'), ('FA', 'FastAPI'), ('FL', 'Flask'), ('SB', 'Spring Boot'), ('NODE', 'Node.js'), ('EXPR', 'Express'), ('NEST', 'NestJS'), ('ASP', 'ASP.NET'), ('LV', 'Laravel'), ('SYM', 'Symfony'), ('ROR', 'Rails'), ('HTML', 'HTML/CSS'), ('REA', 'React'), ('VUE', 'Vue'), ('ANG', 'Angular'), ('NEXT', 'Next.js'), ('NUXT', 'Nuxt.js'), ('SVEL', 'Svelte'), ('TW', 'Tailwind'), ('SASS', 'SASS/SCSS'), ('RDX', 'Redux'), ('WP', 'Webpack'), ('VT', 'Vite'), ('HTMX', 'htmx'), ('SLD', 'SolidJS'), ('PG', 'PostgreSQL'), ('MY', 'MySQL'), ('MG', 'MongoDB'), ('RDS', 'Redis'), ('ES', 'Elasticsearch'), ('SQ', 'SQLite'), ('MAR', 'MariaDB'), ('CAS', 'Cassandra'), ('N4J', 'Neo4j'), ('CH', 'ClickHouse'), ('MEM', 'Memcached'), ('SUPA', 'Supabase'), ('SRL', 'SurrealDB'), ('FLTR', 'Flutter'), ('RN', 'React Native'), ('AND', 'Android'), ('IOS', 'iOS'), ('XAM', 'Xamarin'), ('DKR', 'Docker'), ('K8S', 'Kubernetes'), ('AWS', 'AWS'), ('GCP', 'GCP'), ('AZR', 'Azure'), ('TFMM', 'Terraform'), ('ANS', 'Ansible'), ('JNK', 'Jenkins'), ('GHA', 'GitHub Actions'), ('GLCI', 'GitLab CI'), ('NGX', 'Nginx'), ('APCH', 'Apache'), ('PDM', 'Podman'), ('NPD', 'NumPy/Pandas'), ('TF', 'TensorFlow'), ('PT', 'PyTorch'), ('SKL', 'Scikit-Learn'), ('LC', 'LangChain'), ('OAI', 'OpenAI'), ('SPK', 'Spark'), ('HDP', 'Hadoop'), ('MTL', 'MATLAB'), ('HF', 'Hugging Face'), ('LLM', 'LlamaIndex'), ('GIT', 'Git'), ('REST', 'REST'), ('GQL', 'GraphQL'), ('GRPC', 'gRPC'), ('WS', 'WebSockets'), ('RMQ', 'RabbitMQ'), ('KFK', 'Kafka'), ('CEL', 'Celery'), ('LINX', 'Linux'), ('MSVC', 'Microservices'), ('TEST', 'Testing'), ('SEL', 'Selenium'), ('PW', 'Playwright'), ('CICD', 'CI/CD')], default='PY', max_length=20),
        ),
    ]
