# Generated by Django 6.0.5 on 2026-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_profile', '0009_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
